version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Installation
          command: yarn install
      - run:
          name: Packaging
          command: node_modules/gulp/bin/gulp.js
      - run:
          name: Deploy
          command: ./ftp.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
