version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Installation
          command: yarn install
      - run:
          name: Packaging
          command: npx gulp
      - run:
          name: Deploy
          command: node .circleci/ftp.js
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
