version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: pwd
      - run: ls -la ./.circleci
      - run:
          name: Deploy
          command: ./.circleci/ftp.sh
