version: 2
jobs:
  build-prod:
    docker:
      - image: circleci/node
    environment:
      FTP_ENV: sipacmp
    steps:
      - checkout
      - run:
          name: Installation
          command: yarn install
      - run:
          name: Packaging
          command: npx gulp
      - run:
          name: Deploy
          command: node .circleci/ftp.js
  build-staging:
    docker:
      - image: circleci/node
    environment:
      FTP_ENV: sipacmp-qual
    steps:
      - checkout
      - run:
          name: Installation
          command: yarn install
      - run:
          name: Packaging
          command: npx gulp
      - run:
          name: Deploy
          command: node .circleci/ftp.js
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-prod:
          filters:
            branches:
              only:
                - master
  staging:
    jobs:
      - build-staging:
          filters:
            branches:
              only:
                - develop
