version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Installation
          command: yarn install
      - run:
          name: Packaging
          command: npx gulp
  deploy:
    steps:
      - run:
          name: Deploy
          command: node .circleci/ftp.js
    environment:
      FTP_ENV: sipacmp
  deploy-qual:
    steps:
      - run:
          name: Deploy
          command: node .circleci/ftp.js
    environment:
      FTP_ENV: sipacmp-qual
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
  deploy-qual:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy-qual:
          requires:
            - build
